version: '3'

services:
  app:
    container_name: pittari_estimate
    build:
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - ./:/app:cached
    tty: false
    stdin_open: false
  front:
    container_name: pittari_estimate_front
    build:
      context: ./pittari-estimate-front
    command: yarn serve
    depends_on:
      - app
    ports:
      - '8080:8080'
    volumes:
      - ./pittari-estimate-front:/app
    tty: false
    stdin_open: false
